parser: babel-eslint

extends: airbnb-base

env:
    node: true
    jest: true

rules:
    brace-style: [error, stroustrup, {allowSingleLine: true}]
    indent: [error, 4, {SwitchCase: 1}]
    max-len: [error, 120]
    comma-dangle: [error, always-multiline]
    no-underscore-dangle: [error, {allowAfterThis: true, allowAfterSuper: true}]
    no-plusplus: [error, {allowForLoopAfterthoughts: true}]
    no-use-before-define: [error, {variables: false}]
    object-curly-spacing: [error, never]
    no-console: off
